#-------------------------------
# General Site Settings

title: U N Jha 
logo: 
author: Da_Vicki 
description: Materials Management Consultant 
email:  jhanudaya@gmail.com 
phone: +91-9968282606 
address: Greater Noida - 201308 
copyright: Copyright &copy; 2020 Designed by [Da_Vicki](https://github.com/DaVicki)

menu:
- {name: About, link: '/about'}
- {name: Blog, link: '/blog'}
- {name: Portfolio, link: '/portfolio'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Udaya Narayan Jha <br> Material Management Consultant

social:
- {icon: "ti-facebook", link: "#"}
- {icon: "ti-instagram", link: "#"}
- {icon: "ti-dribbble", link: "#"}
- {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb: >
  I am a seasoned professional with 35 years in Materials Management across multiple work centers.
  Retired as Group General Manager of Materials Management Department (ONGC) overlooking on-shore and 
  off-shore contracts. Efficient in all domains of Materials Management, Warehouse Management, C&F Functions,
  Inventory Management and Contract Management. Proficient in developing and managing highly efficient supply
  chain management. Proficient in Project and Team Management skills.

blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# My Team Section
team:
  - title : "Jack Schenziwe"
    image : "assets/images/team/member-1.png"
    designation : "Project Manager"
    
  - title : "Julias Carlie"
    image : "assets/images/team/member-2.png"
    designation : "Web Developer"
    
  - title : "John Doe"
    image : "assets/images/team/member-3.png"
    designation : "Designer"


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Materials Management, color: '#fdb157', value: '100%'}
- {name: Contract Management, color: '#9473e6', value: '100%'}
- {name: Inventory Management, color: '#bdecf6', value: '100%'}
- {name: Warehouse Management, color: '#ffbcaa', value: '100%'}


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Group General Manager (M.M), icon: 'icon-1.png', date: 'Sep 2018 (retd.)', organization: 'ONGC'}
- {name: General Manager (M.M), icon: 'icon-2.png', date: 'Sep 2012', organization: 'ONGC'}
- {name: Dy. General Manager (M.M), icon: 'icon-3.png', date: 'Sep 2006', organization: 'ONGC'}
- {name: Ch. Manager (M.M), icon: 'icon-1.png', date: 'Sep 1999', organization: 'ONGC'}
- {name: Manager (M.M), icon: 'icon-2.png', date: 'Sep 1997', organization: 'ONGC'}
- {name: Jt. Director (S & P), icon: 'icon-3.png', date: 'Sep 1996', organization: 'ONGC'}
- {name: Dy. Manager (S & P), icon: 'icon-1.png', date: 'Sep 1993', organization: 'ONGC'}
- {name: M.M Officer, icon: 'icon-2.png', date: 'Sep 1983', organization: 'ONGC'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Adv. Diploma in Management, date: '1980', organization: 'Indira Gandhi Open University'}
- {name: Bsc in Chemical Engineering, date: '1974', organization: 'Indian Institute of Technology(IIT) Sindri'}


#-------------------------------
# Services Section

services-title: Services
services:
- {
    name: Consulting,
    icon: ti-palette,
    description: 'Description of Consulting',
    active: # Add true to select section
  }
- {
    name: Consulting,
    icon: ti-vector,
    description: 'Description of Consulting',
    active: true # Add true to select section
  }
- {
    name: Consulting,
    icon: ti-panel,
    description: 'Description of Consulting ',
    active: # Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-4.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-5.png"
    url: "#"


# Portfolio Page
portfolio-label:
- {
    title : "UI/UX Design",
    type : "design"
  }
- {
    title : "BRANDING",
    type : "branding"
  }
- {
    title : "ILLUSTRATION",
    type : "illustration"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"


#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Vicky Jha"
    image: "assets/images/testimonial/client-vicky.jpeg"
    designation : "Investor"
    content : > 
      "Mr U N Jha's professionalism is beyond expectations and his knowledge about
      Materials Management is extraordinary. Insightful, focussed and clear communication is what he 
      brings to every occassion. I enthusiastically recommend him and wish him luck for all his future 
      endeavors. Teaming up with him has sincerely been the most rewarding and pleasant experience of my life.
      Definitely one of the most humble geniuses out there." 
    
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: steve.fruits@email.com
