#-------------------------------
# General Site Settings

title: U N Jha 
logo: 
author: Da_Vicki 
description: Materials Management Consultant 
email:  jhanudaya@gmail.com 
phone: +91-9968282606 
address: Greater Noida - 201308 
copyright: Copyright &copy; 2020 Designed by [Da_Vicki](https://github.com/DaVicki)

menu:
- {name: About, link: '/about'}
- {name: Blog, link: '/blog'}
- {name: Portfolio, link: '/portfolio'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Udaya Narayan Jha <br> <br> Material Management Consultant

social:
- {icon: "ti-linkedin", link: "https://www.linkedin.com/in/udaya-jha-6375a3a7/"}
- {icon: "ti-facebook", link: "https://www.facebook.com/profile.php?id=100005454544720"}
- {icon: "ti-twitter", link: "https://mobile.twitter.com/jhanudaya"}


#-------------------------------
# About (Section and Page)

# About Section
blurb: >
  I am a seasoned professional with 35 years in Materials Management across multiple work centers.
  Retired as Group General Manager of Materials Management Department (ONGC) overlooking on-shore and 
  off-shore contracts. Efficient in all domains of Materials Management, Warehouse Management, C&F Functions,
  Inventory Management and Contract Management. Proficient in developing and managing highly efficient supply
  chain management. Proficient in Project and Team Management skills.

blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : ""
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : ""
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : ""


# My Team Section
team:
  - title : "Jack Schenziwe"
    image : "assets/images/team/member-1.png"
    designation : "Project Manager"
    
  - title : "Julias Carlie"
    image : "assets/images/team/member-2.png"
    designation : "Web Developer"
    
  - title : "John Doe"
    image : "assets/images/team/member-3.png"
    designation : "Designer"


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Materials Management, color: '#fdb157', value: '100%'}
- {name: Contract Management, color: '#9473e6', value: '100%'}
- {name: Inventory Management, color: '#bdecf6', value: '100%'}
- {name: Warehouse Management, color: '#ffbcaa', value: '100%'}


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Group General Manager (M.M), icon: 'icon-1.png', date: 'Jan 2018 (retd.)', organization: 'ONGC'}
- {name: General Manager (M.M), icon: 'icon-2.png', date: 'Jan 2012', organization: 'ONGC'}
- {name: Deputy General Manager (M.M), icon: 'icon-3.png', date: 'Jan 2006', organization: 'ONGC'}
- {name: Chief Manager (M.M), icon: 'icon-1.png', date: 'Jan 1999', organization: 'ONGC'}
- {name: Manager (M.M), icon: 'icon-2.png', date: 'Jan 1996', organization: 'ONGC'}
- {name: Sr Dy Director (M.M), icon: 'icon-3.png', date: 'Jan 1993', organization: 'ONGC'}
- {name: Dy Manager (M.M), icon: 'icon-1.png', date: 'Jan 1998', organization: 'ONGC'}
- {name: Stores & Purchase Officer(S&P), icon: 'icon-2.png', date: 'Jan 1983', organization: 'ONGC'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Adv. Diploma in Management, date: '1980', organization: 'Indira Gandhi Open University'}
- {name: Bsc in Chemical Engineering, date: '1974', organization: 'Indian Institute of Technology(IIT) Sindri'}


#-------------------------------
# Services Section

services-title: Services
services:
- {
    name: Consulting,
    icon: ti-palette,
    description: 'Inventory & Supply Chain Management',
    active: # Add true to select section
  }
- {
    name: Consulting,
    icon: ti-vector,
    description: 'Contract, Materials & Warehouse Management',
    active: true # Add true to select section
  }
- {
    name: Consulting,
    icon: ti-panel,
    description: 'Liasing/Coordination & People Management',
    active: # Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-4.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-5.png"
    url: "#"


# Portfolio Page
portfolio-label:
- {
    title : "UI/UX Design",
    type : "design"
  }
- {
    title : "BRANDING",
    type : "branding"
  }
- {
    title : "ILLUSTRATION",
    type : "illustration"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"


#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Vicky"
    image: "assets/images/testimonial/client-vicky.jpeg"
    designation : "Engineer, Intuit"
    content : > 
      "Mr U N Jha's professionalism is beyond expectations and his knowledge about
      Materials Management is extraordinary. Insightful, focussed and clear communication is what he 
      brings to every occassion. I enthusiastically recommend him and wish him luck for all his future 
      endeavors. Teaming up with him has sincerely been the most rewarding and pleasant experience of my life.
      Definitely one of the most humble geniuses out there." 
    
  - name: "Neeraj Kumar"
    image: "assets/images/testimonial/client-neeraj.jpeg"
    designation: "GM, ONGC"
    content: >
      "Mr Jha is an encyclopedia of MM department, very humble, very straighforward, very easily approachable. He was
      like a mentor for us. I wish him and his family all the best in his future course of life." 
    
  - name: "NJS Hunjan"
    image: "assets/images/testimonial/client-njshunjan.png"
    designation: "GGM, ONGC"
    content: >
      "Mr Jha is an excellent head purchase, he excelled in his job by providing lot of help in procurement. He has gone
      out the way to help. I salute Mr U N Jha, i wish he has a fruitful happy healthy second innings of life"


#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: f/meqnaeoq 
